### ISSUE TITLE
Review XSL templates to ensure completeness in "module" documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#144]
* [x] XSL `xsl/sect_1_scope.xsl` review
* [x] XSL `xsl/sect_2_refs.xsl` review
* [x] XSL `xsl/sect_3_defs.xsl` review
* [x] XSL `xsl/sect_4_express.xsl` review
* [x] XSL `xsl/sect_4_info_reqs.xsl` review
* [x] XSL `xsl/sect_5_main.xsl` review
* [x] XSL `xsl/sect_5_mapping.xsl` review
* [x] XSL `xsl/sect_5_mapping_check.xsl` review
* [x] XSL `xsl/sect_5_mim.xsl` review
* [x] #142 
* [x] XSL `xsl/sect_a_short_names.xsl` review
* [x] XSL `xsl/sect_abstract.xsl` review
* [x] XSL `xsl/sect_b_obj_reg.xsl` review
* [x] XSL `xsl/sect_biblio.xsl` review
* [x] XSL `xsl/sect_c_arm_expg.xsl` review
* [x] XSL `xsl/sect_contents.xsl` review
* [x] XSL `xsl/sect_cover.xsl` review
* [x] XSL `xsl/sect_d_mim_expg.xsl` review
* [x] XSL `xsl/sect_e_exp.xsl` review
* [x] XSL `xsl/sect_e_exp_arm.xsl` review
* [x] XSL `xsl/sect_e_exp_arm_lf.xsl` review
* [x] XSL `xsl/sect_e_exp_mim.xsl` review
* [x] XSL `xsl/sect_e_exp_mim_lf.xsl` review
* [x] #143 
* [x] XSL `xsl/sect_foreword.xsl` review
* [x] XSL `xsl/sect_f_guide.xsl` review
* [x] XSL `xsl/sect_g_change.xsl` review
* [x] XSL `xsl/sect_introduction.xsl` review
* [x] XSL `xsl/sect_isocover.xsl` review
* [x] XSL `xsl/sect_main.xsl` review
* [x] XSL `xsl/sect_modindex.xsl` review
* [x] XSL `xsl/module.xsl` review

**Comment by Intelligent2013** [comment]
> * `xsl/sect_3_defs.xsl`

`sect_3_defs.xsl` updated for https://github.com/metanorma/stepmod2mn/issues/145#issuecomment-2076664788.

**Comment by Intelligent2013** [comment]
These XSLTs:
> * `sect_4_express.xsl`
> * `sect_4_info_reqs.xsl`
> * `sect_5_main.xsl`
> * `sect_5_mapping.xsl`
> * `sect_5_mapping_check.xsl`
> * `sect_5_mim.xsl`


used for the generation
- `sections/04-info_reqs.adoc`
- `sections/05-mim.adoc`

but replaced in https://github.com/metanorma/stepmod2mn/issues/159 by these template:
- `templates/modules/schemas.adoc`

We still need to keep it in `stepmod2mn`, because there are using for the pass-through processing for image processing.

**Comment by Intelligent2013** [comment]
The same for
> * `sect_a_short_names.xsl`
> * `sect_b_obj_reg.xsl`
> * `sect_c_arm_expg.xsl`
> * `sect_d_mim_expg.xsl`
> * `sect_e_exp.xsl`
> * `sect_g_change.xsl`

the resulted adoc replaced by templates:
* `templates/modules/module_annex_short_names.adoc`
* `templates/modules/module_annex_identifier.adoc`
* `templates/modules/module_annex_diagrams_arm.adoc`
* `templates/modules/module_annex_diagrams_mim.adoc`
* `templates/modules/module_annex_listings.adoc`
* `templates/modules/module_annex_change_history.adoc`


These XSLTs are not using in the `stepmod2mn`:
> * sect_e_exp_arm.xsl
> * sect_e_exp_arm_lf.xsl
> * sect_e_exp_mim.xsl
> * sect_e_exp_mim_lf.xsl

because `stepmod-utils` generates .exp files.

**Comment by Intelligent2013** [comment]
> `xsl/sect_abstract.xsl`

`abstract` isn't using, see https://github.com/metanorma/iso-10303-stepmod/issues/33.

**Comment by Intelligent2013** [comment]
> * `xsl/sect_contents.xsl`

`sect_contents.xsl` is using for HTML ToC generation. No need to include it into `stepmod2mn`.

>  - `xsl/sect_foreword.xsl`

`sect_foreword.xsl` contains `<xsl:apply-templates select="." mode="foreword"/>` only, It's not using in `stepmod2mn`'. `<xsl:apply-templates select="." mode="foreword"/>` is called from `stepmod2mn.module.adoc.xsl` directly.

> * `xsl/sect_main.xsl`

`sect_main.xsl` is using for the rendering of whole document on the  one html page. No need to include it into `stepmod2mn.xsl`.

> * `xsl/sect_modindex.xsl`

`sect_modindex.xsl` is using for Index generation. Index generates automatically by Metanorma (by `(((...)))` markup), so no need to include it into `stepmod2mn`.
